execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=1,randomMission=1}] ~ ~ ~ execute @a[scores={playerLoc=111},tag=!informed] ~ ~ ~ function playerManagement/objective/boss
execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=1,randomMission=2}] ~ ~ ~ execute @a[scores={playerLoc=111},tag=!informed] ~ ~ ~ function playerManagement/objective/machine
execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=1,randomMission=3}] ~ ~ ~ execute @a[scores={playerLoc=111},tag=!informed] ~ ~ ~ function playerManagement/objective/supply
execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=1,randomMission=4}] ~ ~ ~ execute @a[scores={playerLoc=111},tag=!informed] ~ ~ ~ function playerManagement/objective/survivor
execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=2,randomMission=1}] ~ ~ ~ execute @a[scores={playerLoc=121},tag=!informed] ~ ~ ~ function playerManagement/objective/boss
execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=2,randomMission=2}] ~ ~ ~ execute @a[scores={playerLoc=121},tag=!informed] ~ ~ ~ function playerManagement/objective/machine
execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=2,randomMission=3}] ~ ~ ~ execute @a[scores={playerLoc=121},tag=!informed] ~ ~ ~ function playerManagement/objective/supply
execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=2,randomMission=4}] ~ ~ ~ execute @a[scores={playerLoc=121},tag=!informed] ~ ~ ~ function playerManagement/objective/survivor
execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=3,randomMission=1}] ~ ~ ~ execute @a[scores={playerLoc=131},tag=!informed] ~ ~ ~ function playerManagement/objective/boss
execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=3,randomMission=2}] ~ ~ ~ execute @a[scores={playerLoc=131},tag=!informed] ~ ~ ~ function playerManagement/objective/machine
execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=3,randomMission=3}] ~ ~ ~ execute @a[scores={playerLoc=131},tag=!informed] ~ ~ ~ function playerManagement/objective/supply
execute @e[type=noxcrew:counter,scores={randomDungeon=1,randomBranch=3,randomMission=4}] ~ ~ ~ execute @a[scores={playerLoc=131},tag=!informed] ~ ~ ~ function playerManagement/objective/survivor
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=1,randomMission=1}] ~ ~ ~ execute @a[scores={playerLoc=211},tag=!informed] ~ ~ ~ function playerManagement/objective/boss
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=1,randomMission=2}] ~ ~ ~ execute @a[scores={playerLoc=211},tag=!informed] ~ ~ ~ function playerManagement/objective/machine
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=1,randomMission=3}] ~ ~ ~ execute @a[scores={playerLoc=211},tag=!informed] ~ ~ ~ function playerManagement/objective/supply
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=1,randomMission=4}] ~ ~ ~ execute @a[scores={playerLoc=211},tag=!informed] ~ ~ ~ function playerManagement/objective/survivor
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=2,randomMission=1}] ~ ~ ~ execute @a[scores={playerLoc=221},tag=!informed] ~ ~ ~ function playerManagement/objective/boss
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=2,randomMission=2}] ~ ~ ~ execute @a[scores={playerLoc=221},tag=!informed] ~ ~ ~ function playerManagement/objective/machine
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=2,randomMission=3}] ~ ~ ~ execute @a[scores={playerLoc=221},tag=!informed] ~ ~ ~ function playerManagement/objective/supply
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=2,randomMission=4}] ~ ~ ~ execute @a[scores={playerLoc=221},tag=!informed] ~ ~ ~ function playerManagement/objective/survivor
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=3,randomMission=1}] ~ ~ ~ execute @a[scores={playerLoc=231},tag=!informed] ~ ~ ~ function playerManagement/objective/boss
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=3,randomMission=2}] ~ ~ ~ execute @a[scores={playerLoc=231},tag=!informed] ~ ~ ~ function playerManagement/objective/machine
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=3,randomMission=3}] ~ ~ ~ execute @a[scores={playerLoc=231},tag=!informed] ~ ~ ~ function playerManagement/objective/supply
execute @e[type=noxcrew:counter,scores={randomDungeon=2,randomBranch=3,randomMission=4}] ~ ~ ~ execute @a[scores={playerLoc=231},tag=!informed] ~ ~ ~ function playerManagement/objective/survivor
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=1,randomMission=1}] ~ ~ ~ execute @a[scores={playerLoc=311},tag=!informed] ~ ~ ~ function playerManagement/objective/boss
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=1,randomMission=2}] ~ ~ ~ execute @a[scores={playerLoc=311},tag=!informed] ~ ~ ~ function playerManagement/objective/machine
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=1,randomMission=3}] ~ ~ ~ execute @a[scores={playerLoc=311},tag=!informed] ~ ~ ~ function playerManagement/objective/supply
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=1,randomMission=4}] ~ ~ ~ execute @a[scores={playerLoc=311},tag=!informed] ~ ~ ~ function playerManagement/objective/survivor
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=2,randomMission=1}] ~ ~ ~ execute @a[scores={playerLoc=321},tag=!informed] ~ ~ ~ function playerManagement/objective/boss
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=2,randomMission=2}] ~ ~ ~ execute @a[scores={playerLoc=321},tag=!informed] ~ ~ ~ function playerManagement/objective/machine
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=2,randomMission=3}] ~ ~ ~ execute @a[scores={playerLoc=321},tag=!informed] ~ ~ ~ function playerManagement/objective/supply
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=2,randomMission=4}] ~ ~ ~ execute @a[scores={playerLoc=321},tag=!informed] ~ ~ ~ function playerManagement/objective/survivor
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=3,randomMission=1}] ~ ~ ~ execute @a[scores={playerLoc=331},tag=!informed] ~ ~ ~ function playerManagement/objective/boss
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=3,randomMission=2}] ~ ~ ~ execute @a[scores={playerLoc=331},tag=!informed] ~ ~ ~ function playerManagement/objective/machine
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=3,randomMission=3}] ~ ~ ~ execute @a[scores={playerLoc=331},tag=!informed] ~ ~ ~ function playerManagement/objective/supply
execute @e[type=noxcrew:counter,scores={randomDungeon=3,randomBranch=3,randomMission=4}] ~ ~ ~ execute @a[scores={playerLoc=331},tag=!informed] ~ ~ ~ function playerManagement/objective/survivor
execute @e[type=noxcrew:counter,scores={randomDungeon=4,randomBranch=1,randomMission=1}] ~ ~ ~ execute @a[scores={playerLoc=411},tag=!informed] ~ ~ ~ function playerManagement/objective/boss
execute @e[type=noxcrew:counter,scores={randomDungeon=4,randomBranch=1,randomMission=2}] ~ ~ ~ execute @a[scores={playerLoc=411},tag=!informed] ~ ~ ~ function playerManagement/objective/machine
execute @e[type=noxcrew:counter,scores={randomDungeon=4,randomBranch=1,randomMission=3}] ~ ~ ~ execute @a[scores={playerLoc=411},tag=!informed] ~ ~ ~ function playerManagement/objective/supply
execute @e[type=noxcrew:counter,scores={randomDungeon=4,randomBranch=1,randomMission=4}] ~ ~ ~ execute @a[scores={playerLoc=411},tag=!informed] ~ ~ ~ function playerManagement/objective/survivor
execute @e[type=noxcrew:counter,scores={randomDungeon=4,randomBranch=2,randomMission=1}] ~ ~ ~ execute @a[scores={playerLoc=421},tag=!informed] ~ ~ ~ function playerManagement/objective/boss
execute @e[type=noxcrew:counter,scores={randomDungeon=4,randomBranch=2,randomMission=2}] ~ ~ ~ execute @a[scores={playerLoc=421},tag=!informed] ~ ~ ~ function playerManagement/objective/machine
execute @e[type=noxcrew:counter,scores={randomDungeon=4,randomBranch=2,randomMission=3}] ~ ~ ~ execute @a[scores={playerLoc=421},tag=!informed] ~ ~ ~ function playerManagement/objective/supply
execute @e[type=noxcrew:counter,scores={randomDungeon=4,randomBranch=2,randomMission=4}] ~ ~ ~ execute @a[scores={playerLoc=421},tag=!informed] ~ ~ ~ function playerManagement/objective/survivor