execute @e[type=noxcrew:counter,scores={missionCount=01}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg2"}]}
execute @e[type=noxcrew:counter,scores={missionCount=02}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg3"}]}
execute @e[type=noxcrew:counter,scores={missionCount=03}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg4"}]}
execute @e[type=noxcrew:counter,scores={missionCount=04}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg5"}]}
execute @e[type=noxcrew:counter,scores={missionCount=05}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg1"}]}
execute @e[type=noxcrew:counter,scores={missionCount=06}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg2"}]}
execute @e[type=noxcrew:counter,scores={missionCount=07}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg3"}]}
execute @e[type=noxcrew:counter,scores={missionCount=08}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg4"}]}
execute @e[type=noxcrew:counter,scores={missionCount=09}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg5"}]}
execute @e[type=noxcrew:counter,scores={missionCount=10}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg1"}]}
execute @e[type=noxcrew:counter,scores={missionCount=11}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg2"}]}
execute @e[type=noxcrew:counter,scores={missionCount=12}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg3"}]}
execute @e[type=noxcrew:counter,scores={missionCount=13}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg4"}]}
execute @e[type=noxcrew:counter,scores={missionCount=14}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg5"}]}
execute @e[type=noxcrew:counter,scores={missionCount=15}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg1"}]}
execute @e[type=noxcrew:counter,scores={missionCount=16}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg2"}]}
execute @e[type=noxcrew:counter,scores={missionCount=17}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg3"}]}
execute @e[type=noxcrew:counter,scores={missionCount=18}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg4"}]}
execute @e[type=noxcrew:counter,scores={missionCount=19}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg5"}]}
execute @e[type=noxcrew:counter,scores={missionCount=20}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg1"}]}
execute @e[type=noxcrew:counter,scores={missionCount=21}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg2"}]}
execute @e[type=noxcrew:counter,scores={missionCount=22}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg3"}]}
execute @e[type=noxcrew:counter,scores={missionCount=23}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg4"}]}
execute @e[type=noxcrew:counter,scores={missionCount=24}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg5"}]}
execute @e[type=noxcrew:counter,scores={missionCount=25}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg1"}]}
execute @e[type=noxcrew:counter,scores={missionCount=26}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg2"}]}
execute @e[type=noxcrew:counter,scores={missionCount=27}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg3"}]}
execute @e[type=noxcrew:counter,scores={missionCount=28}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg4"}]}
execute @e[type=noxcrew:counter,scores={missionCount=29}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg5"}]}
execute @e[type=noxcrew:counter,scores={missionCount=30}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg1"}]}
execute @e[type=noxcrew:counter,scores={missionCount=31}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg10"}]}
execute @e[type=noxcrew:counter,scores={missionCount=32}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg9"}]}
execute @e[type=noxcrew:counter,scores={missionCount=33}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg8"}]}
execute @e[type=noxcrew:counter,scores={missionCount=34}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg7"}]}
execute @e[type=noxcrew:counter,scores={missionCount=35}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg6"}]}
execute @e[type=noxcrew:counter,scores={missionCount=36}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg2"}]}
execute @e[type=noxcrew:counter,scores={missionCount=37}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg3"}]}
execute @e[type=noxcrew:counter,scores={missionCount=38}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg4"}]}
execute @e[type=noxcrew:counter,scores={missionCount=39}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg5"}]}
execute @e[type=noxcrew:counter,scores={missionCount=40}] ~ ~ ~ tellraw @a {"rawtext": [{"translate" : "txt.unlock.msg1"}]}
playsound mission_complete @a 