execute @e[type=noxcrew:counter] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.house"}]}
execute @e[type=noxcrew:counter,tag=!ach.1] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.1_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.1] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.1_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.2] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.2_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.2] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.2_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.3] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.3_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.3] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.3_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.4] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.4_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.4] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.4_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.5] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.5_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.5] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.5_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.6] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.6_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.6] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.6_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.7] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.7_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.7] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.7_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.8] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.8_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.8] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.8_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.9] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.9_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.9] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.9_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.10] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.10_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.10] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.10_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.11] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.11_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.11] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.11_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.12] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.12_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.12] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.12_unlocked"}]}
execute @e[type=noxcrew:counter,tag=!ach.13] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.13_locked"}]}
execute @e[type=noxcrew:counter,tag=ach.13] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.13_unlocked"}]}
execute @e[type=noxcrew:counter] ~ ~ ~ tellraw @p {"rawtext": [{"translate" : "txt.ach.house"}]}