gamerule commandblockoutput false
gamerule commandblocksenabled true
gamerule doentitydrops true
gamerule dofiretick false
gamerule doimmediaterespawn false
gamerule doinsomnia false
gamerule domobloot true
gamerule domobspawning true
gamerule dotiledrops false
gamerule doweathercycle false
gamerule drowningdamage true
gamerule falldamage true
gamerule firedamage true
gamerule keepinventory true
gamerule mobgriefing false
gamerule naturalregeneration true
gamerule pvp false
gamerule sendcommandfeedback false
gamerule showcoordinates false
gamerule showdeathmessages true
gamerule showtags false
gamerule tntexplodes true
mobevent minecraft:wandering_trader_event false