scoreboard objectives add randomDungeon dummy
scoreboard objectives add randomBranch dummy
scoreboard objectives add selectedBranch dummy
scoreboard objectives add randomMission dummy
scoreboard objectives add randomBoss dummy
scoreboard objectives add randomMach dummy
scoreboard objectives add randomSup dummy
scoreboard objectives add randomSurv dummy
scoreboard objectives add greetings dummy
scoreboard objectives add interrupt dummy
scoreboard objectives add splitBossOutput dummy
scoreboard objectives add RNGpartLoc dummy
scoreboard objectives add playerLoc dummy
scoreboard objectives add playerLocCheck dummy
scoreboard objectives add zCount110 dummy
scoreboard objectives add zCount120 dummy
scoreboard objectives add zCount130 dummy
scoreboard objectives add zCount210 dummy
scoreboard objectives add zCount220 dummy
scoreboard objectives add zCount230 dummy
scoreboard objectives add zCount310 dummy
scoreboard objectives add zCount320 dummy
scoreboard objectives add zCount330 dummy
scoreboard objectives add zCount410 dummy
scoreboard objectives add zCount420 dummy
scoreboard objectives add randomReplParts dummy
scoreboard objectives add tutLoc dummy
scoreboard objectives add tutLocScrap dummy
scoreboard objectives add tutLocLandmark dummy
scoreboard objectives add tutText dummy
scoreboard objectives add scraps dummy
scoreboard objectives add spawnSetting dummy
scoreboard objectives add missionCount dummy